#!/usr/bin/env python3

# ============================================================
# CronGhost — Scheduled Task Shadow Scanner
# Tier 3 — Cryptographic baseline + smart false-positive filter
# ============================================================
# What is new in Tier 3:
#   - Baseline snapshot system
#     First run: learns your clean system
#     Every run after: compares against that baseline
#     Any change from baseline = real threat, not guess
#   - Smart false positive filter
#     Knows about Kali-specific files that are legitimately
#     outside dpkg (nmap.sh, dotnet, pam-auth-update files)
#   - Confidence system
#     Every finding gets a confidence % not just a score
#     LOW confidence = probably safe, just watch it
#     HIGH confidence = real threat, act now
#   - Only shows findings that matter
#     No more noise from clean system files
# ============================================================

import os
import sys
import platform
import socket
import subprocess
import hashlib
import json
from datetime import datetime

# ── Colors ──────────────────────────────────────────────────

RESET  = "\033[0m"
WHITE  = "\033[97m"
GRAY   = "\033[90m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"

# ── Baseline file path ───────────────────────────────────────
# This is where CronGhost saves your clean system snapshot
# Hidden in /var/lib so it survives across runs

BASELINE_PATH = "/var/lib/cronghost/baseline.json"

# ── Extended whitelist ───────────────────────────────────────
# Files that are legitimately outside dpkg on Kali Linux
# These are dropped by tools, not apt, and are always safe

KALI_KNOWN_SAFE = {
    # VTE terminal
    "/etc/profile.d/vte-2.91.sh",
    "/etc/profile.d/vte.sh",
    # Shell tools
    "/etc/profile.d/bash_completion.sh",
    "/etc/profile.d/bash_completion",
    # Kali specific
    "/etc/profile.d/kali.sh",
    "/etc/profile.d/locale.sh",
    "/etc/profile.d/colorls.sh",
    # Nmap adds this itself outside dpkg — safe on Kali
    "/etc/profile.d/nmap.sh",
    # Microsoft dotnet installer drops this outside dpkg — safe
    "/etc/profile.d/dotnet-cli-tools-bin-path.sh",
    # Java
    "/etc/profile.d/jvm.sh",
    # Standard profile files
    "/etc/profile.d/apps-bin-path.sh",
    "/etc/profile.d/cedilla.sh",
    "/etc/profile.d/input-method-config.sh",
    "/etc/profile.d/80-systemd-osc-context.sh",
    "/etc/profile.d/gawk.csh",
    # /etc/environment is configured by Kali setup — safe
    "/etc/environment",
    # PAM files generated by pam-auth-update — not directly by dpkg
    "/etc/pam.d/common-auth",
    "/etc/pam.d/common-account",
    "/etc/pam.d/common-password",
    "/etc/pam.d/common-session",
    "/etc/pam.d/common-session-noninteractive",
    # Standard cron files
    "/etc/cron.daily/apt-compat",
    "/etc/cron.daily/dpkg",
    "/etc/cron.daily/logrotate",
    "/etc/cron.daily/man-db",
    "/etc/cron.daily/passwd",
    "/etc/cron.weekly/man-db",
    "/etc/cron.weekly/update-notifier-common",
    "/etc/cron.monthly/unattended-upgrades",
    # Kali tool cron jobs — legitimate
    "/etc/cron.d/php",
    "/etc/cron.d/e2scrub_all",
    "/etc/cron.d/sysstat",
    "/etc/cron.d/.placeholder",
    "/etc/cron.d/john",
    # Standard PAM files modified by Kali
    "/etc/pam.d/chfn",
    "/etc/pam.d/chpasswd",
    "/etc/pam.d/chsh",
    "/etc/pam.d/login",
    "/etc/pam.d/newusers",
    "/etc/pam.d/other",
    "/etc/pam.d/passwd",
    "/etc/pam.d/runuser",
    "/etc/pam.d/runuser-l",
    "/etc/pam.d/su",
    "/etc/pam.d/su-l",
}

# ── High confidence attack patterns ─────────────────────────
# These patterns are ONLY used by attackers — never in
# legitimate system files. Finding these = real threat.

HIGH_CONFIDENCE_PATTERNS = [
    {"pattern": "bash -i >& /dev/tcp/", "score": 95, "reason": "classic reverse shell"},
    {"pattern": "/dev/tcp/",            "score": 90, "reason": "raw TCP reverse shell"},
    {"pattern": "bash -i",              "score": 75, "reason": "interactive bash spawn"},
    {"pattern": "nc -e /bin/bash",      "score": 95, "reason": "netcat reverse shell"},
    {"pattern": "nc -e /bin/sh",        "score": 95, "reason": "netcat reverse shell"},
    {"pattern": "/dev/shm/",            "score": 80, "reason": "hides in shared memory"},
    {"pattern": "base64 -d | bash",     "score": 90, "reason": "decode and execute payload"},
    {"pattern": "python -c 'import",    "score": 70, "reason": "python reverse shell pattern"},
    {"pattern": "python3 -c 'import",   "score": 70, "reason": "python reverse shell pattern"},
    {"pattern": "curl | bash",          "score": 85, "reason": "download and execute"},
    {"pattern": "wget -O- | bash",      "score": 85, "reason": "download and execute"},
    {"pattern": "curl | sh",            "score": 85, "reason": "download and execute"},
]

# Medium confidence — could be legitimate or malicious
MEDIUM_CONFIDENCE_PATTERNS = [
    {"pattern": "curl ",   "score": 35, "reason": "downloads remote content"},
    {"pattern": "wget ",   "score": 35, "reason": "downloads remote content"},
    {"pattern": "/tmp/",   "score": 40, "reason": "references /tmp directory"},
    {"pattern": "base64",  "score": 40, "reason": "base64 encoding present"},
    {"pattern": "pam_exec","score": 60, "reason": "PAM exec entry"},
    {"pattern": "chmod +x","score": 30, "reason": "makes file executable"},
]

# ── The 14 persistence locations ────────────────────────────

LOCATIONS = [
    {"id":  1, "name": "/etc/crontab",              "path": "/etc/crontab",             "kind": "file"},
    {"id":  2, "name": "/var/spool/cron/crontabs/", "path": "/var/spool/cron/crontabs", "kind": "directory"},
    {"id":  3, "name": "/etc/cron.d/",              "path": "/etc/cron.d",              "kind": "directory"},
    {"id":  4, "name": "/etc/cron.daily/",          "path": "/etc/cron.daily",          "kind": "directory"},
    {"id":  5, "name": "/etc/cron.hourly/",         "path": "/etc/cron.hourly",         "kind": "directory"},
    {"id":  6, "name": "/etc/cron.weekly/",         "path": "/etc/cron.weekly",         "kind": "directory"},
    {"id":  7, "name": "/etc/cron.monthly/",        "path": "/etc/cron.monthly",        "kind": "directory"},
    {"id":  8, "name": "/etc/anacrontab",           "path": "/etc/anacrontab",          "kind": "file"},
    {"id":  9, "name": "systemd timers",            "path": "/etc/systemd/system",      "kind": "systemd"},
    {"id": 10, "name": "/etc/profile.d/",           "path": "/etc/profile.d",           "kind": "directory"},
    {"id": 11, "name": "/etc/environment",          "path": "/etc/environment",         "kind": "file"},
    {"id": 12, "name": "PAM exec module",           "path": "/etc/pam.d",               "kind": "pam"},
    {"id": 13, "name": "/etc/rc.local",             "path": "/etc/rc.local",            "kind": "file"},
    {"id": 14, "name": "XDG autostart",             "path": "/etc/xdg/autostart",       "kind": "directory"},
]

# ── Helpers ──────────────────────────────────────────────────

def clear_screen():
    os.system("clear")

def print_line():
    print(GRAY + "  " + "─" * 62 + RESET)

def print_banner():
    print(WHITE + BOLD + r"""
  ____                  ____  _               _   
 / ___|_ __ ___  _ __  / ___|| |__   ___  ___| |_ 
| |   | '__/ _ \| '_ \| |  _ | '_ \ / _ \/ __| __|
| |___| | | (_) | | | | |_| || | | | (_) \__ \ |_ 
 \____|_|  \___/|_| |_|\____||_| |_|\___/|___/\__|
""" + RESET)
    print(GRAY + "  Scheduled Task Shadow Scanner — v3.0.0 — Tier 3" + RESET)
    print()

def print_system_info(baseline_exists):
    hostname  = socket.gethostname()
    os_name   = platform.system() + " " + platform.release()
    scan_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    uid       = os.geteuid()
    user_lbl  = WHITE + "root" + RESET if uid == 0 else YELLOW + "not root — some scans limited" + RESET
    mode      = CYAN + "Tier 3 — cryptographic baseline" + RESET
    baseline  = GREEN + "active — comparing against known clean state" + RESET if baseline_exists else YELLOW + "not set — run option 4 to create baseline" + RESET

    print_line()
    print()
    print(GRAY + "  Hostname    " + RESET + WHITE + hostname  + RESET)
    print(GRAY + "  System      " + RESET + WHITE + os_name   + RESET)
    print(GRAY + "  Scan time   " + RESET + WHITE + scan_time + RESET)
    print(GRAY + "  Running as  " + RESET + user_lbl)
    print(GRAY + "  Mode        " + RESET + mode)
    print(GRAY + "  Baseline    " + RESET + baseline)
    print()

# ── Tier 3 — Baseline system ─────────────────────────────────

def hash_file(filepath):
    """
    Create a SHA256 hash of a file's content.
    If the file changes even one byte the hash changes.
    This is how we detect tampering.
    """
    try:
        h = hashlib.sha256()
        with open(filepath, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return None

def create_baseline():
    """
    Tier 3 — Snapshot your clean system.
    Walks all 14 locations, hashes every file,
    saves the hashes to a JSON file.
    Next time CronGhost runs it compares against this.
    """
    print()
    print(WHITE + "  Creating baseline snapshot of your clean system..." + RESET)
    print(GRAY  + "  Run this once on a clean system." + RESET)
    print(GRAY  + "  Every future scan compares against this." + RESET)
    print()

    os.makedirs(os.path.dirname(BASELINE_PATH), exist_ok=True)

    baseline = {
        "created"  : datetime.now().isoformat(),
        "hostname" : socket.gethostname(),
        "files"    : {}
    }

    all_files = collect_all_files()
    count     = 0

    for fp in all_files:
        h = hash_file(fp)
        if h:
            baseline["files"][fp] = {
                "hash"    : h,
                "size"    : os.path.getsize(fp),
                "mtime"   : os.path.getmtime(fp),
            }
            count += 1
            print(GRAY + f"  hashed  {fp}" + RESET)

    with open(BASELINE_PATH, "w") as f:
        json.dump(baseline, f, indent=2)

    print()
    print(GREEN + f"  Baseline saved. {count} files recorded." + RESET)
    print(GREEN + f"  Location: {BASELINE_PATH}" + RESET)
    print()
    print(GRAY  + "  From now on CronGhost will alert on ANY change" + RESET)
    print(GRAY  + "  to these files — even a single byte difference." + RESET)
    print()

def load_baseline():
    """Load the saved baseline if it exists."""
    try:
        with open(BASELINE_PATH, "r") as f:
            return json.load(f)
    except Exception:
        return None

def check_baseline_changes(baseline):
    """
    Tier 3 — Compare current files against baseline.
    Returns list of files that changed, were added, or removed.
    """
    if not baseline:
        return []

    changes   = []
    all_files = collect_all_files()

    # Check for modified or new files
    for fp in all_files:
        if fp in KALI_KNOWN_SAFE:
            continue
        current_hash = hash_file(fp)
        if not current_hash:
            continue

        if fp in baseline["files"]:
            saved_hash = baseline["files"][fp]["hash"]
            if current_hash != saved_hash:
                changes.append({
                    "type"    : "modified",
                    "filepath": fp,
                    "detail"  : "file content changed since baseline",
                    "confidence": 90,
                })
        else:
            # File did not exist when baseline was created
            changes.append({
                "type"    : "new",
                "filepath": fp,
                "detail"  : "file did not exist when baseline was created",
                "confidence": 85,
            })

    # Check for deleted files (rare but rootkits do this)
    for fp in baseline["files"]:
        if not os.path.exists(fp) and fp not in KALI_KNOWN_SAFE:
            changes.append({
                "type"    : "deleted",
                "filepath": fp,
                "detail"  : "file existed in baseline but is now gone",
                "confidence": 70,
            })

    return changes

# ── Smart detection ──────────────────────────────────────────

def is_known_safe(filepath):
    """Check if a file is in our extended Kali safe list."""
    return filepath in KALI_KNOWN_SAFE

def scan_content(filepath):
    """
    Smart content scanner.
    First checks high confidence patterns (real attacks).
    Then checks medium confidence patterns (possible attacks).
    Returns score, confidence, and matched patterns.
    """
    score      = 0
    confidence = 0
    hits       = []

    try:
        with open(filepath, "r", errors="ignore") as f:
            content = f.read()

        # High confidence first — these are never in legit files
        for p in HIGH_CONFIDENCE_PATTERNS:
            if p["pattern"] in content:
                score      += p["score"]
                confidence  = max(confidence, 85)
                hits.append({"pattern": p["pattern"], "score": p["score"],
                             "reason": p["reason"], "confidence": "HIGH"})

        # Medium confidence — need more context
        if not hits:
            for p in MEDIUM_CONFIDENCE_PATTERNS:
                if p["pattern"] in content:
                    score      += p["score"]
                    confidence  = max(confidence, 45)
                    hits.append({"pattern": p["pattern"], "score": p["score"],
                                "reason": p["reason"], "confidence": "MEDIUM"})

    except PermissionError:
        pass
    except Exception:
        pass

    return min(score, 100), confidence, hits

def check_package_manager(filepath):
    """Ask dpkg if it knows this file."""
    try:
        result = subprocess.run(
            ["dpkg", "-S", filepath],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            pkg = result.stdout.split(":")[0].strip()
            return True, pkg
        return False, None
    except Exception:
        return None, None

def get_file_age(filepath):
    """Get file creation time and check for odd hours."""
    try:
        st      = os.stat(filepath)
        created = datetime.fromtimestamp(st.st_ctime)
        hour    = created.hour
        days    = (datetime.now() - created).days
        info    = f"created {created.strftime('%Y-%m-%d %H:%M')} ({days}d ago)"
        odd     = 1 <= hour <= 5
        return odd, info
    except Exception:
        return False, "unknown"

def get_owner(filepath):
    """Check file owner."""
    try:
        uid = os.stat(filepath).st_uid
        if uid == 0:
            return True, "root"
        import pwd
        try:
            name = pwd.getpwuid(uid).pw_name
        except Exception:
            name = str(uid)
        return False, f"{name} (uid {uid})"
    except Exception:
        return True, "unknown"

def analyze_file(filepath):
    """
    Full smart analysis of one file.
    Combines all checks into a single verdict with confidence score.
    Only returns a finding if confidence is high enough to matter.
    """
    # Always skip known safe files
    if is_known_safe(filepath):
        return None

    content_score, content_conf, hits = scan_content(filepath)
    pkg_known,     pkg_name           = check_package_manager(filepath)
    odd_hour,      age_info           = get_file_age(filepath)
    is_root,       owner_info         = get_owner(filepath)

    # Build final confidence score
    # Each factor contributes to how confident we are
    final_confidence = content_conf

    # Not in dpkg + has suspicious content = very high confidence
    if pkg_known is False and content_score > 0:
        final_confidence = min(final_confidence + 30, 95)

    # Not in dpkg alone (no content hits) = medium confidence
    elif pkg_known is False and content_score == 0:
        final_confidence = max(final_confidence, 35)

    # Created at odd hour adds confidence
    if odd_hour:
        final_confidence = min(final_confidence + 20, 95)

    # Not root owned = very suspicious
    if not is_root:
        final_confidence = min(final_confidence + 25, 95)

    # If confidence is below 40 and no high-confidence content hits
    # it is probably a legitimate file — skip it
    high_conf_hits = [h for h in hits if h.get("confidence") == "HIGH"]
    if final_confidence < 40 and not high_conf_hits:
        return None

    # Determine verdict
    if final_confidence >= 80:
        verdict = "critical"
    elif final_confidence >= 60:
        verdict = "suspicious"
    else:
        verdict = "low"

    return {
        "filepath"      : filepath,
        "verdict"       : verdict,
        "confidence"    : final_confidence,
        "content_score" : content_score,
        "content_hits"  : hits,
        "pkg_known"     : pkg_known,
        "pkg_name"      : pkg_name,
        "odd_hour"      : odd_hour,
        "age_info"      : age_info,
        "owner_info"    : owner_info,
        "is_root"       : is_root,
    }

# ── File collection ──────────────────────────────────────────

def collect_all_files():
    """Collect all files from all 14 locations."""
    files = []
    for loc in LOCATIONS:
        path = loc["path"]
        try:
            if loc["kind"] == "file":
                if os.path.exists(path):
                    files.append(path)
            elif loc["kind"] in ("directory", "pam"):
                if os.path.isdir(path):
                    for f in os.listdir(path):
                        fp = os.path.join(path, f)
                        if os.path.isfile(fp):
                            files.append(fp)
            elif loc["kind"] == "systemd":
                if os.path.isdir(path):
                    for f in os.listdir(path):
                        if f.endswith(".timer"):
                            files.append(os.path.join(path, f))
        except PermissionError:
            pass
    return files

def get_files_for_location(loc):
    """Get files for one specific location."""
    files = []
    path  = loc["path"]
    try:
        if loc["kind"] == "file":
            if os.path.exists(path):
                files.append(path)
        elif loc["kind"] in ("directory", "pam"):
            if os.path.isdir(path):
                for f in os.listdir(path):
                    fp = os.path.join(path, f)
                    if os.path.isfile(fp):
                        files.append(fp)
        elif loc["kind"] == "systemd":
            if os.path.isdir(path):
                for f in os.listdir(path):
                    if f.endswith(".timer"):
                        files.append(os.path.join(path, f))
    except PermissionError:
        pass
    return files

# ── Scanner ──────────────────────────────────────────────────

def scan_all_locations(baseline):
    print_line()
    print()
    print(WHITE + "  Scanning all 14 persistence locations..." + RESET)
    print()

    all_results     = []
    baseline_alerts = check_baseline_changes(baseline) if baseline else []
    total           = len(LOCATIONS)

    for loc in LOCATIONS:
        files   = get_files_for_location(loc)
        flagged = []

        for fp in files:
            result = analyze_file(fp)
            if result:
                flagged.append(result)

        num  = f"{loc['id']:2d}/{total}"
        name = loc["name"].ljust(30)

        if flagged:
            worst = max(r["confidence"] for r in flagged)
            if worst >= 80:
                status = RED    + "[!!]" + RESET
                note   = RED    + "critical" + RESET
            elif worst >= 60:
                status = YELLOW + "[!!]" + RESET
                note   = YELLOW + "suspicious" + RESET
            else:
                status = CYAN   + "[??]" + RESET
                note   = CYAN   + "low confidence" + RESET
        else:
            status = GREEN + "[OK]" + RESET
            note   = ""

        print(f"  {status}  {GRAY}{num}{RESET}  {WHITE}{name}{RESET}  {note}")

        if flagged:
            all_results.append({"location": loc, "results": flagged})

    print()
    return all_results, baseline_alerts

# ── Results display ──────────────────────────────────────────

def confidence_bar(conf):
    filled = int(conf / 5)
    empty  = 20 - filled
    color  = RED if conf >= 80 else YELLOW if conf >= 60 else CYAN
    return f"[{color}{'█' * filled}{GRAY}{'░' * empty}{RESET}] {conf}%"

def print_results(all_results, baseline_alerts):
    total   = len(LOCATIONS)
    flagged = len(all_results)
    clean   = total - flagged

    print_line()
    print()
    print(WHITE + "  Scan results:" + RESET)
    print()
    print(GRAY + "  Total scanned      " + RESET + WHITE + str(total)  + RESET)
    print(GRAY + "  Clean              " + RESET + GREEN + str(clean)  + RESET)
    print(GRAY + "  Suspicious files   " + RESET + (RED + str(flagged) + RESET if flagged else GREEN + "0" + RESET))
    print(GRAY + "  Baseline changes   " + RESET + (RED + str(len(baseline_alerts)) + RESET if baseline_alerts else GREEN + "0" + RESET))
    print()

    if not all_results and not baseline_alerts:
        print(GREEN + "  System is clean. No threats detected." + RESET)
        print()
        return

    # Show baseline changes first — these are highest confidence
    if baseline_alerts:
        print_line()
        print()
        print(RED + "  Baseline violations — these files changed since your clean snapshot:" + RESET)
        print()
        for alert in baseline_alerts:
            type_label = {
                "modified": RED    + "[CHANGED] " + RESET,
                "new"     : RED    + "[NEW FILE]" + RESET,
                "deleted" : YELLOW + "[DELETED] " + RESET,
            }.get(alert["type"], YELLOW + "[CHANGE]  " + RESET)

            print(f"  {type_label}  " + WHITE + alert["filepath"] + RESET)
            print(GRAY + "  Confidence  " + RESET + confidence_bar(alert["confidence"]))
            print(GRAY + "  Detail      " + RESET + alert["detail"])
            print()

    # Show smart detection results
    if all_results:
        print_line()
        print()
        print(WHITE + "  Smart detection findings:" + RESET)
        print()

        for item in all_results:
            for r in item["results"]:
                vc    = RED if r["verdict"] == "critical" else YELLOW if r["verdict"] == "suspicious" else CYAN
                label = r["verdict"].upper()

                print(vc + f"  [{label}]" + RESET + "  " + WHITE + r["filepath"] + RESET)
                print()
                print(GRAY + "  Confidence    " + RESET + confidence_bar(r["confidence"]))
                print()

                # Package manager check
                if r["pkg_known"] is True:
                    print(GRAY + "  Package       " + RESET + GREEN + f"known — {r['pkg_name']}" + RESET)
                elif r["pkg_known"] is False:
                    print(GRAY + "  Package       " + RESET + RED + "NOT in dpkg — manually placed" + RESET)
                else:
                    print(GRAY + "  Package       " + RESET + GRAY + "could not check" + RESET)

                # Owner
                oc = GREEN if r["is_root"] else RED
                print(GRAY + "  Owner         " + RESET + oc + r["owner_info"] + RESET)

                # Age
                ac = RED if r["odd_hour"] else GRAY
                print(GRAY + "  File age      " + RESET + ac + r["age_info"] + RESET)

                # Content hits
                if r["content_hits"]:
                    print(GRAY + "  Content hits  " + RESET)
                    for h in r["content_hits"][:4]:
                        conf_color = RED if h["confidence"] == "HIGH" else YELLOW
                        print(GRAY + f"    {conf_color}[{h['confidence']}]{RESET}" +
                              GRAY + f"  +{h['score']:2d}  " + RESET +
                              YELLOW + h["pattern"].ljust(20) + RESET +
                              GRAY + h["reason"] + RESET)

                print()

# ── Menu ─────────────────────────────────────────────────────

def show_menu(all_results, baseline_alerts, baseline):
    print_line()
    print()
    print(WHITE + "  Options:" + RESET)
    print()
    print(GRAY + "  1)  " + RESET + "Run scan again")
    print(GRAY + "  2)  " + RESET + "Export report to file")
    print(GRAY + "  3)  " + RESET + "Update baseline with current system state")
    print(GRAY + "  4)  " + RESET + ("Create baseline (first time setup)" if not baseline else "Rebuild baseline from scratch"))
    print(GRAY + "  5)  " + RESET + "Quit")
    print()

    while True:
        try:
            choice = input("  Enter choice: ").strip()
        except (KeyboardInterrupt, EOFError):
            print(GRAY + "\n  Goodbye.\n" + RESET)
            sys.exit(0)

        if choice == "1":
            main()
            return
        elif choice == "2":
            export_report(all_results, baseline_alerts)
        elif choice in ("3", "4"):
            create_baseline()
        elif choice == "5":
            print(GRAY + "\n  Goodbye.\n" + RESET)
            sys.exit(0)
        else:
            print(GRAY + "  Invalid choice. Enter 1-5." + RESET)

def export_report(all_results, baseline_alerts):
    filename = f"cronghost_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    lines    = [
        "CronGhost — Tier 3 Threat Report",
        f"Time     : {datetime.now()}",
        f"Hostname : {socket.gethostname()}",
        "=" * 62,
    ]

    if baseline_alerts:
        lines.append("\nBASELINE VIOLATIONS:")
        for a in baseline_alerts:
            lines += [
                f"  Type       : {a['type'].upper()}",
                f"  File       : {a['filepath']}",
                f"  Confidence : {a['confidence']}%",
                f"  Detail     : {a['detail']}",
            ]

    if all_results:
        lines.append("\nSMART DETECTION FINDINGS:")
        for item in all_results:
            for r in item["results"]:
                lines += [
                    f"\n  Verdict    : {r['verdict'].upper()}",
                    f"  File       : {r['filepath']}",
                    f"  Confidence : {r['confidence']}%",
                    f"  Package    : {'known — ' + str(r['pkg_name']) if r['pkg_known'] else 'NOT in dpkg'}",
                    f"  Owner      : {r['owner_info']}",
                    f"  Age        : {r['age_info']}",
                ]
                for h in r.get("content_hits", []):
                    lines.append(f"  Hit        : [{h['confidence']}] {h['pattern']} — {h['reason']}")

    if not all_results and not baseline_alerts:
        lines.append("No threats found.")

    with open(filename, "w") as f:
        f.write("\n".join(lines))
    print(GREEN + f"\n  Report saved to {filename}\n" + RESET)

# ── Main ─────────────────────────────────────────────────────

def main():
    if platform.system() != "Linux":
        print(RED + "Error: CronGhost only runs on Linux." + RESET)
        sys.exit(1)

    if os.geteuid() != 0:
        print(RED + "Error: CronGhost must run as root." + RESET)
        print(GRAY + "Run:  sudo cronghost" + RESET)
        sys.exit(1)

    clear_screen()
    print_banner()

    baseline = load_baseline()
    print_system_info(baseline is not None)

    all_results, baseline_alerts = scan_all_locations(baseline)
    print_results(all_results, baseline_alerts)
    show_menu(all_results, baseline_alerts, baseline)

if __name__ == "__main__":
    main()
